---
- name: Creates directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: "extract artifact."
  unarchive:
    src: /home/circleci/project/artifact.tar.gz
    dest: /home/ubuntu/backend

- name: "stop app."
  become: true
  shell: pm2 stop default
  ignore_errors: yes

- name: "start app."
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm install
    pm2 start npm -- start
